openapi: 3.2.0
info:
  title: Risk Management Risk Modifiers API
  version: v2
servers:
- url: https://api.dome9.com/
  description: US region
- url: https://api.{region}.dome9.com/
  description: Other regions
  variables:
    region:
      enum:
      - eu1
      - ap1
      - ap2
      - ap3
      - cace1
      default: eu1
security:
- basic: []
tags:
- name: Risk Modifiers
paths:
  /v2/erm/asset-types/supported-types:
    get:
      tags:
      - Risk Modifiers
      summary: Get
      operationId: RiskModifiers_Get_get_/v2/erm/asset-types/supported-types
      responses:
        '200':
          description: ''
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
      description: Get all supported assets per risk modifiers
components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
x-readme:
  explorer-enabled: true
  proxy-enabled: true
