openapi: 3.2.0
info:
  title: Inventory - AWS Security, Identity and Compliance CloudWAF…
  version: v2
servers:
- url: https://api.dome9.com/
  description: US region
- url: https://api.{region}.dome9.com/
  description: Other regions
  variables:
    region:
      enum:
      - eu1
      - ap1
      - ap2
      - ap3
      - cace1
      default: eu1
security:
- basic: []
tags:
- name: CloudWAF Regional
paths:
  /v2/CloudWAFRegional:
    get:
      tags:
      - CloudWAF Regional
      operationId: CloudWAFRegional_Get_get_/v2/CloudWAFRegional
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Falconetix.Model.AwsWAFRegionalViewModel'
      description: ''
      summary: Get
components:
  schemas:
    Falconetix.Model.AwsWAFRegionalViewModel:
      type: object
      properties:
        name:
          type: string
        webACLId:
          type: string
        wafRegionalResources:
          type: array
          items:
            type: string
        tags:
          type: object
          additionalProperties:
            type: string
  securitySchemes:
    basic:
      type: http
      scheme: basic
x-readme:
  explorer-enabled: true
  proxy-enabled: true
