openapi: 3.2.0
info:
  title: Inventory - AWS Global Cloud Region API
  version: v2
servers:
- url: https://api.dome9.com/
  description: US region
- url: https://api.{region}.dome9.com/
  description: Other regions
  variables:
    region:
      enum:
      - eu1
      - ap1
      - ap2
      - ap3
      - cace1
      default: eu1
security:
- basic: []
tags:
- name: Cloud Region
paths:
  /v2/CloudRegion:
    get:
      tags:
      - Cloud Region
      operationId: CloudRegion_Get_get_/v2/CloudRegion
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dome9.Web.Api.CloudAwsRegion.CloudRegionViewModel'
      description: ''
      summary: Get
components:
  schemas:
    Dome9.Web.Api.CloudAwsRegion.CloudRegionViewModel:
      type: object
      properties:
        cloudAccountId:
          format: uuid
          type: string
          example: 00000000-0000-0000-0000-000000000000
        accountId:
          format: int64
          type: integer
        externalAccountNumber:
          type: string
        regionName:
          type: string
        endpoint:
          type: string
        isDefaultEndpoint:
          type: boolean
        isEnabled:
          type: boolean
  securitySchemes:
    basic:
      type: http
      scheme: basic
x-readme:
  explorer-enabled: true
  proxy-enabled: true
